### ISSUE TITLE
Pylint inside latest image fails

### ISSUE THREAD

**Issue by sipani909** [Docker-Hub-frolvlad/docker-alpine-python3#16]
```
Using docker image sha256:80484c205b6584533f3e1333a2d0059d8a954488a005723885a619e63f90bc60 for frolvlad/alpine-python3:latest with digest frolvlad/alpine-python3@sha256:69f108d85ddb473123c5fdae3f415aee900f0bccd2e78523f7ceba23a9688b0e ...
$ pip install --upgrade pylint
Collecting pylint
  Downloading pylint-2.7.4-py3-none-any.whl (346 kB)
Collecting astroid<2.7,>=2.5.2
  Downloading astroid-2.5.3-py3-none-any.whl (226 kB)
Collecting isort<6,>=4.2.5
  Downloading isort-5.8.0-py3-none-any.whl (103 kB)
Collecting lazy-object-proxy>=1.4.0
  Downloading lazy-object-proxy-1.6.0.tar.gz (44 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting mccabe<0.7,>=0.6
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting toml>=0.7.1
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting wrapt<1.13,>=1.11
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Building wheels for collected packages: lazy-object-proxy, wrapt
  Building wheel for lazy-object-proxy (PEP 517): started
  Building wheel for lazy-object-proxy (PEP 517): finished with status 'done'
  Created wheel for lazy-object-proxy: filename=lazy_object_proxy-1.6.0-cp38-cp38-linux_x86_64.whl size=11347 sha256=a2cdfc4c790f1845040c286bfeb322d8b976fb5da6511db945ef03c33e5e6913
  Stored in directory: /root/.cache/pip/wheels/25/31/33/2d2448eb3f67feb67321b65057a2fc4404cd4a6d6392cb51fb
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'done'
  Created wheel for wrapt: filename=wrapt-1.12.1-py3-none-any.whl size=19553 sha256=71a6922d081cf7ee454aafe09827828ba0d1132d56d9fabf56380260fae273ed
  Stored in directory: /root/.cache/pip/wheels/5f/fd/9e/b6cf5890494cb8ef0b5eaff72e5d55a70fb56316007d6dfe73
Successfully built lazy-object-proxy wrapt
Installing collected packages: wrapt, lazy-object-proxy, toml, mccabe, isort, astroid, pylint
Successfully installed astroid-2.5.3 isort-5.8.0 lazy-object-proxy-1.6.0 mccabe-0.6.1 pylint-2.7.4 toml-0.10.2 wrapt-1.12.1
WARNING: You are using pip version 20.3.3; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
$ pylint --rcfile=./testbed_ms/pylintrc testbed_ms/
Traceback (most recent call last):
  File "/usr/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/usr/lib/python3.8/site-packages/pylint/__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/lib/python3.8/site-packages/pylint/lint/run.py", line 317, in __init__
    linter.load_plugin_modules(plugins)
  File "/usr/lib/python3.8/site-packages/pylint/lint/pylinter.py", line 503, in load_plugin_modules
    module = astroid.modutils.load_module_from_name(modname)
  File "/usr/lib/python3.8/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'util'
```

**Comment by frol** [comment]
I cannot reproduce it:

![image](https://user-images.githubusercontent.com/304265/116012136-17d4d600-a5ff-11eb-9735-c34f4ec84bdf.png)

![image](https://user-images.githubusercontent.com/304265/116012141-215e3e00-a5ff-11eb-894e-9966acf1aa9e.png)
